print ("##########################")
print ("#                        #")
print ("#   Farel Putra Liandi   #")
print ("#     2610820310013      #")
print ("#                        #")
print ("##########################")